dist: trusty
language: python
sudo: required
python:
  - "2.7"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest

# Run in parallel for each mysql version being tested
env:
  global:
    - CI_NODE_TOTAL=3
  matrix:
  - MONGO_TEST=2.6.9 CI_NODE_INDEX=1
  - MONGO_TEST=3.0.14 CI_NODE_INDEX=2
  - MONGO_TEST=3.2.10 CI_NODE_INDEX=3

before_script:
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
  - echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list
  - echo "deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.0.list
  - echo "deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.2.list
  - . /etc/lsb-release && echo "deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
  - . /etc/lsb-release && echo "deb http://apt.postgresql.org/pub/repos/apt/ $DISTRIB_CODENAME-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list
  - wget -qO- https://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
  - wget --quiet -O - https://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc | sudo apt-key add -
  - sudo apt-get update

# command to build and run tests
script:
  - sudo apt-get install -y --force-yes mongodb-org=$MONGO_TEST
  - sudo service mongod restart
  - sudo service postgresql stop
  - sudo apt-get remove -q 'postgresql-*'
  - sudo apt-get update -q
  - sudo apt-get -y install --force-yes "postgresql-10" "postgresql-contrib-10"
  - sudo sed -i "s/#listen_addresses = 'localhost'/listen_addresses = '*'/" /etc/postgresql/10/main/postgresql.conf
  - sudo echo "host    all             all             all                     md5" >> /etc/postgresql/10/main/pg_hba.conf
  - sudo echo "client_encoding = utf8" >> /etc/postgresql/10/main/postgresql.conf
  - sudo service postgresql restart
  - psql -c "CREATE ROLE DBA WITH SUPERUSER LOGIN PASSWORD 'dba';" -U postgres
  - sudo apt-get install -y --force-yes rethinkdb=2.2*
  - sudo sed "s/^#\(.*bind.*\)/bind=all/" /etc/rethinkdb/default.conf.sample | sudo tee /etc/rethinkdb/instances.d/instance1.conf
  - sudo service rethinkdb restart
  - pip install 'rethinkdb<2.3'
  - python setup.py install
  - pytest --capture=no tests
  - sudo apt-get install -y --force-yes rethinkdb
  - sudo service rethinkdb restart
  - pip install 'rethinkdb~=2.3'
  - python setup.py install
  - pytest --capture=no tests
